CREATE TABLE [dbo].[GetActiveDirectoryUsers]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CanonicalName] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[DomainName] AS (left([CanonicalName],charindex('/',[CanonicalName])-(1))),
[sAMAccountName] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[OperationalUnit] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[FirstName] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[LastName] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[DisplayName] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[email] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[EmailAddress] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[ImpliedAcount] AS (case  when charindex('@',[EmailAddress])>(0) AND charindex('.',[EmailAddress])>charindex('@',[EmailAddress]) then (substring([EmailAddress],charindex('@',[EmailAddress])+(1),(charindex('.',[EmailAddress])-charindex('@',[EmailAddress]))-(1))+'\')+substring([EmailAddress],(1),charindex('@',[EmailAddress])-(1)) else '' end) PERSISTED,
[StreetAddress] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[PostalCode] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[HomePhone] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[MobilePhone] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[OfficePhone] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Fax] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Company] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Organization] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Department] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Title] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Description] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[Office] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[extensionAttribute1] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[extensionAttribute2] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[extensionAttribute3] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[extensionAttribute4] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[extensionAttribute5] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[AccountExpires] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[AccountIsEnabled] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[PasswordLastSet] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[PasswordAge] AS (case  when isdate([PasswordLastSet])=(1) then datediff(day,[PasswordLastSet],getdate()) else (0) end),
[PasswordExpires] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[PasswordNeverExpires] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[PasswordIsExpired] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[LastLogonTimestamp] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[CreatedDate] [datetime] NULL,
[DWCreatedDate] [datetime] NULL CONSTRAINT [DF__GetActiveDirectoryUsers__DWCreatedDate] DEFAULT (getdate()),
[DWUpdatedDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GetActiveDirectoryUsers] ADD CONSTRAINT [PK__GetActiveDirectoryUsers_sAMAccountName] PRIMARY KEY CLUSTERED  ([CanonicalName], [sAMAccountName]) ON [PRIMARY]
GO
